export const defaults = {
  provider: "openrouter",
  model: "cohere/north-mini-code:free",
  temperature: 0.2,
  maxIterations: 12,
  maxTokens: 2048,
  requestTimeoutMs: 120000,
  queueDelayMs: 350,
  agentMode: "build",
  permissionMode: "standard",
  commandAllowlist: "npm test,npm run,node --check,git status,git diff",
  enabledTools: "",
  developerMode: false,
  developerId: "",
  uncensoredModel: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
  fallbackModels: "cohere/north-mini-code:free,qwen/qwen3-coder:free,meta-llama/llama-3.3-70b-instruct:free,google/gemma-4-26b-a4b-it:free,openai/gpt-oss-20b:free",
  cloudflareGatewayUrl: "https://ai.itzadhi.in",
  pet: "sprite",
  streaming: true,
  actions: true,
  status: true,
  compact: false,
  workspace: process.cwd(),
}
