export const defaults = {
  provider: "openrouter",
  model: "cohere/north-mini-code:free",
  temperature: 0.2,
  maxIterations: 12,
  maxTokens: 2048,
  requestTimeoutMs: 120000,
  queueDelayMs: 350,
  platform: process.platform,
  agentMode: "build",
  permissionMode: "standard",
  commandAllowlist: "node,npm,npx,python,py,pip,git status,git diff,git log,git branch,git rev-parse,git add,git commit,where,dir,type,echo,powershell -NoProfile,pwsh -NoProfile,cmd /c",
  enabledTools: "",
  developerMode: false,
  developerId: "",
  uncensoredModel: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
  fallbackModels: "cohere/north-mini-code:free,qwen/qwen3-coder:free,meta-llama/llama-3.3-70b-instruct:free,google/gemma-4-26b-a4b-it:free,openai/gpt-oss-20b:free",
  cloudflareGatewayUrl: "https://ai.itzadhi.in",
  updateCheck: true,
  autoUpdate: false,
  updateCheckIntervalHours: 6,
  updateRegistryUrl: "https://registry.npmjs.org",
  pet: "sprite",
  streaming: true,
  actions: true,
  status: true,
  compact: false,
  workspace: process.cwd(),
}
